### ISSUE TITLE
Cannot read property 'xdr:wsDr' of null

### ISSUE THREAD

**Issue by yeongjet** [q86002618/excel-image-transformer#2]
很遗憾没能跑通，我运行后会报以下错误
```
const twoCellAnchors = drawingXmlObj["xdr:wsDr"]["xdr:twoCellAnchor"] as Array<any> || [];
                                        ^
TypeError: Cannot read property 'xdr:wsDr' of null
```

解决办法是
在_resolveDrawing函数里只解析drawing1.xml和drawing1.xml.rels:
```ts
  private _resolveDrawing(sheetId: string) {
    const drawingXmlObj = this._parseMetaXmlToObject(`xl/drawings/drawing${sheetId}.xml`)
    const drawingRelXmlObj = this._parseMetaXmlToObject(`xl/drawings/_rels/drawing${sheetId}.xml.rels`)
    return { drawingXmlObj, drawingRelXmlObj };
  }
```
不明白为什么要解析`worksheets/sheet${sheetId}.xml`和`worksheets/_rels/sheet${sheetId}.xml.rels`

**Comment by gilboom** [comment]
> 很遗憾没能跑通，我运行后会报以下错误
> 
> ```
> const twoCellAnchors = drawingXmlObj["xdr:wsDr"]["xdr:twoCellAnchor"] as Array<any> || [];
>                                         ^
> TypeError: Cannot read property 'xdr:wsDr' of null
> ```
> 
> 解决办法是
> 在_resolveDrawing函数里只解析drawing1.xml和drawing1.xml.rels:
> 
> ```ts
>   private _resolveDrawing(sheetId: string) {
>     const drawingXmlObj = this._parseMetaXmlToObject(`xl/drawings/drawing${sheetId}.xml`)
>     const drawingRelXmlObj = this._parseMetaXmlToObject(`xl/drawings/_rels/drawing${sheetId}.xml.rels`)
>     return { drawingXmlObj, drawingRelXmlObj };
>   }
> ```
> 
> 不明白为什么要解析`worksheets/sheet${sheetId}.xml`和`worksheets/_rels/sheet${sheetId}.xml.rels`

我记得当时在做这个修改的时候，是因为发现通过 xl/drawings/_rels/drawing${sheetId}.xml这样的方式拿到的 drawing.xml 不一定是对的，也就是说 drawing 后面的数字可能不是 sheetId

**Comment by gilboom** [comment]
这个问题在 1.0.5 的版本中已经修复了，可以更新一下最新版

**Comment by yeongjet** [comment]
谢谢

**Comment by gilboom** [comment]
> 谢谢

不客气，我也没想到我这个工具有人用 orz，所以没怎么维护
